spring.application.name=agent-orchestrator-service
server.port=8086

adapter.geocoder.url=${GEOCODER_URL:https://nominatim.openstreetmap.org}
adapter.serpapi.url=${SERPAPI_URL:https://serpapi.com}
adapter.serpapi.api.key=${SERPAPI_API_KEY:}

#microservices.user.url=${USER_SERVICE_URL:http://localhost:8081}
#microservices.shop.url=${SHOP_SERVICE_URL:http://localhost:8082}
microservices.product.url=${PRODUCT_SERVICE_URL:http://localhost:8083}
#microservices.order.url=${ORDER_SERVICE_URL:http://localhost:8084}
microservices.agent.url=${AGENT_SERVICE_URL:http://localhost:8085}

